name: Development workflow

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: npm install
      - name: Lint with eslint
        run: npm run lint
      - name: Run unit tests
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          npm config set dathost:datHostEmail $EMAIL
          npm config set dathost:datHostPass $PASSWORD
          npm run test
      # Upload package to NPM before pulling package version.
      - name: Get release version
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: echo ::set-env name=DATHOST_VERSION::$(npm info dathost version)
      - name: Build with esbuild
        run: npm run build
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "${{ env.DATHOST_VERSION }}"
          files: dist/**