name: Production workflow

on:
  push:
    branches:
    - Production

env:
  INPUT_TOKEN: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: npm install
      - name: Lint with eslint
        run: npm run lint
      - name: Run unit tests
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          npm config set dathost:datHostEmail $EMAIL
          npm config set dathost:datHostPass $PASSWORD
          npm run test
      - name: Pack to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Get Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'
      - name: Delete npmrc
        run: rm -f ./.npmrc
      - name: Build with esbuild
        run: npm run build
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{steps.version.outputs.prop}}"
          prerelease: false
          title: "${{steps.version.outputs.prop}}"
          files: dist/**
      - name: Build docs
        run: npm run docs
      - name: Upload docs to dathost.wardpearce.com
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./docs/
          server-dir: ts/docs/
