name: Development workflow

on:
  push:
    branches:
    - Development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: npm install
      - name: Lint with eslint
        run: npm run lint
      - name: Run unit tests
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          npm config set dathost:datHostEmail $EMAIL
          npm config set dathost:datHostPass $PASSWORD
          npm run test
      - name: Build with esbuild
        run: npm run build
